# Generated by Django 4.1.3 on 2022-11-11 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
